#!/usr/bin/env bash
# Script that configures Nginx sever with a customer header
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debiab.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
file="/etc/nginx/sites-available/default"
sed -i  "211 add_header X-Served-By $HOSTNAME;" $file
service nginx start
