#!/usr/bin/env bash
# Install and sets up haproxy

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers
echo"
  listen load_balancer
  binf *:80
  mode http
  balance roundrobin
  option httpclose
  option forwardfor
  server 64786-web-01 3.84.237.80 check
  server 64786-web-02 100.25.203.47 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start