#!/usr/bin/env bash
# Fixed a web server to run Nginx as the nginx user listening on prt 8080.
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx/conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
